# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='info',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
